### ISSUE TITLE
 如何自定义插件呢？

### ISSUE THREAD

**Issue by rustbomb** [itellyou-com/am-editor#1]

**Comment by itellyou-com** [comment]
内容有点多，后期补充文档

**Comment by itellyou-com** [comment]
https://editor.aomao.com/plugin/tutorials

**Comment by rustbomb** [comment]
https://editor.aomao.com/plugin/tutorials 是插件的配置文档，更想知道的是插件的开发文档，如何开发自己的插件。

**Comment by itellyou-com** [comment]
是否有清除缓存呢？
