### ISSUE TITLE
markdown的表格是否能转换成表格插件模式？

### ISSUE THREAD

**Issue by akaylh** [itellyou-com/am-editor#10]

**Comment by itellyou-com** [comment]
所有的markdown粘贴转换还在优化

**Comment by itellyou-com** [comment]
已修复

**Comment by rustbomb** [comment]
在edge和chrome下粘贴markdown的表格，有提示转换，确定后，并没有转换成功。
![2021-05-26 17 00 03](https://user-images.githubusercontent.com/437330/119632995-e3de1200-be43-11eb-9951-0ee6dd352512.gif)
