### ISSUE TITLE
表格组件再内容渲染的时候报错

### ISSUE THREAD

**Issue by fz51** [itellyou-com/am-editor#11]
demo 来自 https://github.com/itellyou-com/am-editor/blob/master/docs/demo/content.tsx
在编辑器中，添加了table 组件，编辑器中正常，但是非编辑模式下，显示报错

![image](https://user-images.githubusercontent.com/16314961/118343240-53a5f000-b55a-11eb-9cb5-5a992d0239f2.png)

**Comment by itellyou-com** [comment]
已修复
