### ISSUE TITLE
demo中评论的两个按钮逻辑好像反了

### ISSUE THREAD

**Issue by rustbomb** [itellyou-com/am-editor#15]
![image](https://user-images.githubusercontent.com/437330/119930028-3db01a80-bfb1-11eb-9406-6461b79a7abf.png)
ok变成了取消，cancel变成了确定

**Comment by itellyou-com** [comment]
翻译搞反了。。。

**Comment by rustbomb** [comment]
demo上复制粘贴也无效了。

**Comment by itellyou-com** [comment]
应该是图片和文件两个插件把粘贴事件拦截了，我查查

**Comment by itellyou-com** [comment]
好了
