### ISSUE TITLE
使用工具栏的话就不支持vite吗？

### ISSUE THREAD

**Issue by Thornchg** [itellyou-com/am-editor#16]
使用了工具栏（有引入antd-design-vue）
控制台报错
Uncaught Error: Dynamic require of "..../node_modules/ant-design-vue/lib/style/index.css" is not supported

**Comment by itellyou-com** [comment]
也没有异步引用样式哇，我是用 father-build 构建的。不知道是不是这个问题

**Comment by Thornchg** [comment]
Uncaught Error: Dynamic require of "...../node_modules/ant-design-vue/lib/style/index.css" is not supported
    at __require (chunk-G3IZEHTJ.js?v=1ef58579:11)
    at css.js:3

vite esm是不支持require的吧
我看了https://github.com/vueComponent/ant-design-vue/issues/3570 这个回答
![image](https://user-images.githubusercontent.com/42759223/120093717-88b36480-c14e-11eb-8156-046282f28ed0.png)
这块是否应该去引用esm组件的
ant-design-vue/es/tooltip
编译我不是太懂。。。

**Comment by itellyou-com** [comment]
我引用es打包发布一个试一下

**Comment by itellyou-com** [comment]
@Thornchg 试试看这三个插件？

- @aomao/toolbar-vue@2.1.3
- @aomao/plugin-codeblock-vue@2.1.2
- @aomao/plugin-link-vue@2.1.2

**Comment by Thornchg** [comment]
可以了可以了。我试了toolbar。其他还没试 

但是出现很多警告
![image](https://user-images.githubusercontent.com/42759223/120095952-5ceaab80-c15b-11eb-8953-c10de5b73a80.png)

**Comment by itellyou-com** [comment]
警告就是 设置 Boolean 类型的时候，只能是 true 或者 false 不能是 undefined。因为我是直接参考复制 toolbar (react)版本的的代码，所以这里直接把 Boolean 设置的为 Object 的，不影响使用。有时间了这些细节可以优化一下。

**Comment by Thornchg** [comment]
好的。谢谢

**Comment by Thornchg** [comment]
@itellyou-com 
link 插件这边发现有两个问题
** Link 插件 markdown 语法为[文本](链接地址) 回车后触发 **
这边实际使用发现是后面加空格触发的
还有一个是如果是在最后一行 末行。  我输入完  “[文本](链接地址)”  直接回车。光标跳到下一行。然后再按删除键 光标回到上一行末尾。 这时不管是敲空格。还是敲空格后再回车  怎么操作  都不会触发。 需要整行删除掉重新编辑。最后敲空格才行

**Comment by Thornchg** [comment]
那个toolbar的问题。。。开发环境可以了。 但是打包部署滞后。 正式环境不行。。。。
![image](https://user-images.githubusercontent.com/42759223/120132321-bfe04f00-c1fc-11eb-8ae2-bb9b12c74e2f.png)

**Comment by Thornchg** [comment]
> 那个toolbar的问题。。。开发环境可以了。 但是打包部署滞后。 正式环境不行。。。。
> ![image](https://user-images.githubusercontent.com/42759223/120132321-bfe04f00-c1fc-11eb-8ae2-bb9b12c74e2f.png)

报错。搞错了。 toolbar可以。   是codeblock的问题。 开发环境可以。 但是打包部署的话。 配置了codeblock插件。就会报这个错误

**Comment by Thornchg** [comment]
> 那个toolbar的问题。。。开发环境可以了。 但是打包部署滞后。 正式环境不行。。。。
> ![image](https://user-images.githubusercontent.com/42759223/120132321-bfe04f00-c1fc-11eb-8ae2-bb9b12c74e2f.png)

抱歉。搞错了。 toolbar可以。   是codeblock的问题。 开发环境可以。 但是打包部署的话。 配置了codeblock插件。就会报这个错误

**Comment by itellyou-com** [comment]
https://github.com/itellyou-com/am-editor/blob/master/plugins/codeblock-vue/src/component/mode.ts
会是这里问题吗

**Comment by Thornchg** [comment]
![image](https://user-images.githubusercontent.com/42759223/120151697-2a09eb80-c21f-11eb-8679-65951b033f0c.png)

.../node_modules/@aomao/plugin-codeblock-vue/dist/index.esm.js
![image](https://user-images.githubusercontent.com/42759223/120151773-41e16f80-c21f-11eb-81ca-68e736a7e113.png)

应该是这块。你看下。 vite 里不支持require

**Comment by itellyou-com** [comment]
https://github.com/itellyou-com/am-editor/releases/tag/%40aomao%2Fengine%402.1.2

**Comment by Thornchg** [comment]
@itellyou-com 
你好。我在自定义antdv主题时。 异步组件引入编辑器时会发生个别组件样式会被编辑器内部给覆盖了。我看了下源码

这些用到antdv的组件。引入组件样式的地方。 不知道能否去引入ant-design-vue/es/.../style/index.less 文件。这样编辑器也能同时应用我自定义主题后的颜色和样式。 不知道可不可以
![image](https://user-images.githubusercontent.com/42759223/120635771-6d728d00-c49f-11eb-8944-8cf5a8cc6e7d.png)
