### ISSUE TITLE
公式内容闪动

### ISSUE THREAD

**Issue by rustbomb** [itellyou-com/am-editor#23]
**Describe the bug**

公式内容会跳动

**To Reproduce**

**Screenshots**

![2021-06-10 19 51 17](https://user-images.githubusercontent.com/437330/121520387-6e6a6800-ca25-11eb-810d-9738f8083728.gif)

**Desktop (please complete the following information):**
 - OS: Mojave 10.14.6
 - Browser: safari、edge
 - Version 14.3.3、 89.0.774.68

**Comment by itellyou-com** [comment]
没这系统，先搁着吧

**Comment by itellyou-com** [comment]
观察发现，可能有的人一直挂着页面，没有刷新，导致那边是旧版本插件出现的
