### ISSUE TITLE
在vue3项目中引入项目会遇到一些问题。

### ISSUE THREAD

**Issue by Mr-meng54** [itellyou-com/am-editor#25]
1. 项目中的vue3版本如果和editor的版本不相同会出现多版本共存问题会有警告，并且toolbar不能正常渲染。
2. 修改为相同版本后警告消除，toolbar中除了dropdown渲染的标题、字号、文本样式、对齐方式有效，其他的点击没有效果。
3. button按钮执行triggerClick函数时，autoExecute始终为false，无法执行命令。

**Comment by itellyou-com** [comment]
你的vue3版本号是多少

**Comment by itellyou-com** [comment]
已修复 https://github.com/itellyou-com/am-editor/releases/tag/%40aomao%2Ftoolbar-vue%402.2.10
