### ISSUE TITLE
暂时没有支持vue2的版本吗？

### ISSUE THREAD

**Issue by denggp** [itellyou-com/am-editor#26]
目前系统框架是vue2的版本，这个目前有2的vue插件吗

**Comment by itellyou-com** [comment]
引擎就是纯 JavaScript 的，所有前端库都可以用

下面这三个插件有使用vue3渲染部分UI
* toolbar-vue 几乎全部
* codeblock-vue 语言选择下拉框
* link-vue 链接编辑表单

**Comment by denggp** [comment]
刚好用到这几个
oolbar-vue 几乎全部
codeblock-vue 语言选择下拉框
link-vue 链接编辑表单
就很尴尬  2和3不兼容

**Comment by itellyou-com** [comment]
@denggp 这就需要把这三个插件降到vue2，toolbar 插件需要一些代码量。群里有人做过

**Comment by denggp** [comment]
怎么进群讨论？

**Comment by itellyou-com** [comment]
@denggp 在自述文件里面有群号
