### ISSUE TITLE
FontSize and FontFamily tool wont work on pasted text  and Seletion changed after command triggered  

### ISSUE THREAD

**Issue by byoungd** [itellyou-com/am-editor#30]
**Describe the bug**
Copy some text from the editor and paste them just after, then select them all (including the original text), use toolbar FontSize or FontFamily wont work properly.

**To Reproduce**
1. Go to editor.aomao.com demo site
2. copy some text and paste just after it
3. select these text 
4. try to run FontSize or FontFamily tool

**Expected behavior**
We expected  the effect takes on all the selection but Only the first paragraph change and the selection change too!  You  can found these texts are nested in *span*  in dom.

**Screenshots**

https://user-images.githubusercontent.com/16145783/125182139-097d7a00-e23e-11eb-94d9-27fadfad8f7e.mp4

**Desktop (please complete the following information):**
 - OS:window10
 - Browse chrome
 - Version  91.0.4472.124（stable） （64 bit）

---
*中文*

选择一段文字然后直接复制在他的后面，然后选中他们，尝试使用字体或者字号的功能时，发现只有第一段或前几段的文字产生了效果而不是选取的所有段落，而且选取发生了改变，如视频中的演示所示。

**Comment by itellyou-com** [comment]
同样环境下，我这边无法复现。不过刚刚在粘贴时进行了一小点改动。你刷新再试一下看看呢？

**Comment by byoungd** [comment]
@itellyou-com 刚在https://editor.aomao.com/进行多次测试 似乎已经解决了这个问题！
