### ISSUE TITLE
行内代码需要在反引号后面加个空格才能触发转换，且引号内会多出一个空格

### ISSUE THREAD

**Issue by akaylh** [itellyou-com/am-editor#4]
![2021-04-12 14 21 45](https://user-images.githubusercontent.com/437330/114349629-bfcbb780-9b9a-11eb-9e61-62cd51ce996e.gif)

如上图所示，添加一行文字，通过两个反引号实现行内代码功能，需要在后一个绰号位置添加空格，才能完成格式的转换，同时行内代码内会多出一个空格。

**Comment by itellyou-com** [comment]
多了个空格，已修复

要空格触发，因为考虑到可能会有人单纯使用那个字符
