### ISSUE TITLE
有vue的示例代码吗

### ISSUE THREAD

**Issue by itellyou-com** [itellyou-com/am-editor#5]
有vue的示例代码吗

_Originally posted by @ZYX518 in https://github.com/itellyou-com/am-editor/issues/2#issuecomment-817626994_

https://github.com/itellyou-com/am-editor/tree/master/demo-vue

**Comment by ZYX518** [comment]
摸摸哒

**Comment by ZYX518** [comment]
vue咋引入工具栏，渲染工具栏，传入插件名称QAQ

**Comment by itellyou-com** [comment]
> vue咋引入工具栏，渲染工具栏，传入插件名称QAQ

工具栏现在只有 React 版本的，可以通过 `engine.command.execute` 执行命令 `engine.command.queryState` 查询插件状态

**Comment by ZYX518** [comment]
一个页面有俩个编辑器，可以同时协作编辑嘛，两个编辑器的数据互相不影响，目前我只能对一个编辑器进行协作。QAQ

**Comment by itellyou-com** [comment]
要对 ot-server 中用于测试的文档id “demo”修改为一个前段进行ws连接时传过来的独立id，否则都将视为对demo id对应的文档内容进行编辑

**Comment by itellyou-com** [comment]
@ZYX518 `@aomao/toolbar-vue` 工具栏有了

**Comment by ZYX518** [comment]
![image](https://user-images.githubusercontent.com/76080302/115170475-56482d80-a0f3-11eb-9176-d928b8be0093.png)
每一个框都是一个富文本编辑器，能再这个页面实现协作编辑吗，
//实例化协作编辑客户端，传入当前编辑器引擎实例
            //         const otClient = new OTClient(engine);
这好像只能是单个富文本编辑

**Comment by itellyou-com** [comment]
> ![image](https://user-images.githubusercontent.com/76080302/115170475-56482d80-a0f3-11eb-9176-d928b8be0093.png)
> 每一个框都是一个富文本编辑器，能再这个页面实现协作编辑吗，
> //实例化协作编辑客户端，传入当前编辑器引擎实例
> // const otClient = new OTClient(engine);
> 这好像只能是单个富文本编辑

OT 服务，是针对单人单篇文章为一个链接的。一人多篇文章那就得多个连接

**Comment by l54808821** [comment]
@big-camel  您好，https://github.com/itellyou-com/am-editor/tree/master/demo-vue  vue的协作demo好像过期了呢

**Comment by big-camel** [comment]
> @big-camel 您好，https://github.com/itellyou-com/am-editor/tree/master/demo-vue vue的协作demo好像过期了呢

没有vue协作现成的演示，但是用法都是一样的。

协作客户端是ts的，没有vue 和react，https://github.com/red-axe/am-editor/blob/master/examples/react/components/editor/ot/client.ts 

服务端是nodejs的 https://github.com/red-axe/am-editor/tree/master/ot-server
