### ISSUE TITLE
支持vue2吗

### ISSUE THREAD

**Issue by oooowl** [itellyou-com/am-editor#9]

**Comment by itellyou-com** [comment]
直接用的VUE最新的，只有UI渲染的位置使用了VUE

**Comment by akaylh** [comment]
现在所有的插件都能在vue环境正常工作吗？因为我们的应用是vue开发的，看您介绍说editor是react的开发，不知道是能否都正常使用。

**Comment by itellyou-com** [comment]
> 现在所有的插件都能在vue环境正常工作吗？因为我们的应用是vue开发的，看您介绍说editor是react的开发，不知道是能否都正常使用。

在部分 ui 使用原生js做渲染比较困难下， 都是使用的前端框架渲染。这些渲染仅仅用作于 ui 呈现展示和用户端参数输入，不参与编辑器的逻辑处理。所以换成其它任何前端渲染库都可以使用

前端框架都是使用最新的库

react 17

vue 3

下面这个三个插件有 react 和 vue 区别，ui库都是使用的 antdv

toolbar-vue 工具栏，全部使用框架渲染
codeblock-vue 代码块，语言选择下拉使用框架渲染
link-vue 链接，文字输入修改使用框架渲染

如果非要使用 vue2 的话，那就得修改这三个插件 vue 渲染代码
